name = "ChainTables"
uuid = "9916ecaa-2162-471d-8083-d1d45c3def62"
version = "0.1.0"
authors = ["Jon Alm Eriksen <jon.alm.eriksen@protonmail.com>"]

[deps]
SHA = "ea8e919c-243c-51af-8825-aaa63cd721ce"

[compat]
SHA = "0.7.0"
julia = "1.10"

[extras]
Tables = "bd369af6-aec1-5ad0-b16a-f7cc5008161c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Tables"]
